Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2018-11, with the labels that each got.

#287 Move Ga attr to allow override from outside.
  workspace/utilities/lib/share-link.xsl
Labels: enhancement, ready to merge

#288 Add basic theme viewer (Colors, dimensions, spacing)
  workspace/assets/css/vars/theme.xml
  workspace/dev/theme/index.ui
  workspace/dev/theme/theme.css
Labels: enhancement, ready to merge

#269 Sync build config
  workspace/assets/tasks/complexity.js
  workspace/assets/tasks/jshint.js
Labels: enhancement, ready to merge

#296 standardized naming for metas
  start.sql
  workspace/data-sources/data.page_metas.php
  workspace/data-sources/data.site_config.php
  workspace/utilities/lib/master-alt-link-metas.xsl
  workspace/utilities/lib/master-share-metas.xsl
  workspace/utilities/lib/master-title.xsl
  workspace/utilities/site-variables.xsl
Labels: change requested, enhancement

#303 Add new Dev tool for img without alt
  workspace/assets/css/dev/dev.less
  workspace/assets/js/dev/panel.js
Labels: enhancement, ready to merge

#240 Add text-decoration-skip-ink class
  workspace/assets/css/lib/class-text-decoration.less
Labels: enhancement, ready to merge

#299 Create function for prefix of sticky (for safari).
  workspace/assets/css/core/fct-position.less
  workspace/assets/css/lib/class-position.less
Labels: bug, ready to merge

#297 Completely removed menu-admin and added admin-tools
  workspace/assets/css/com/menu-admin.less
  workspace/assets/css/main.less
  workspace/utilities/admin-tools/admin-tools.css
  workspace/utilities/admin-tools/admin-tools.xsl
  workspace/utilities/admin-tools/widgets/widget-build.xsl
  workspace/utilities/admin-tools/widgets/widget-debug.xsl
  workspace/utilities/admin-tools/widgets/widget-edit-entry.xsl
  workspace/utilities/admin-tools/widgets/widget-flush-cache.xsl
  workspace/utilities/admin-tools/widgets/widget-logout.xsl
  workspace/utilities/com/site-header.xsl
  workspace/utilities/lib/edit-buttons.xsl
  workspace/utilities/lib/menu-admin.xsl
  workspace/utilities/master/master-head.xsl
  workspace/utilities/master/master.xsl
  workspace/utilities/site-imports.xsl
Labels: change requested, enhancement, need feedback

#305 Fix twitter share link
  workspace/utilities/lib/share-link.xsl
Labels: bug
