Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2018-10, with the labels that each got.

#284 Added humans <3
  humans.txt
Labels: enhancement

#295 When jitting an image, also check its filname
  workspace/utilities/lib/render-image.xsl
Labels: bug

#292 Added bundle push dev as scripts
  workspace/assets/package.json
Labels: enhancement

#289 Add more dom element in the dom view (main, nav, button, a)
  workspace/assets/js/dev/panel.js
Labels: enhancement, ready to merge

#291 Replace attributes with CSS for w3c validation
  workspace/utilities/lib/iframe-copyright-288.xsl
Labels: enhancement, ready to merge

#294 Avoid conflict with the escape key and general popup
  workspace/assets/js/dev/panel.js
Labels: enhancement, need feedback, ready to merge
