Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2019-07, with the labels that each got.

#351 Allow custom domain for edit button.
  workspace/utilities/admin-tools/admin-tools.xsl
  workspace/utilities/admin-tools/widgets/widget-edit-entry.xsl
Labels: enhancement, ready to merge

#348 added keys and added things to our cheap modrnzr
  workspace/assets/js.json
  workspace/assets/js/utils/global.js
  workspace/assets/js/utils/keys.js
  workspace/assets/tasks/complexity.js
Labels: bug, ready to merge

#359 (feat) Disable direct access to .php[\d] and .phar
  htaccess.txt
Labels: enhancement

#356 Re set the image type
  workspace/utilities/lib/picture.xsl
Labels: bug, ready to merge

#358 [css-core] Add animation-delay function
  workspace/assets/css/core/fct-animation.less
Labels: enhancement, ready to merge

#353 Use new namespace for keys
  workspace/assets/js/dev/panel.js
Labels: bug, ready to merge

#344 (fix) Fallback on http-host if no twitter site domain
  workspace/utilities/site-variables.xsl
Labels: enhancement
