Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2019-08, with the labels that each got.

#350 (feat) Add ninja img template
  workspace/utilities/lib/ninja-img.xsl
Labels: enhancement, ready to merge

#349 (fix) use site-name var instead of absolute and wrong path or config var
  workspace/utilities/com/site-header-logo-link.xsl
Labels: change requested, enhancement

#355 (chore) Point to the new tracking.js file
  workspace/assets/js.json
Labels: wait before merge
