Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2019-12, with the labels that each got.

#385 (feat) Clean css theme files
  workspace/assets/tasks/clean.js
Labels: proposal

#367 Added design-mode to dev panel
  workspace/assets/js/dev/panel.js
Labels: enhancement

#405 Added dev task in build
  workspace/assets/Gruntfile.js
Labels: enhancement, proposal, ready to merge

#346 (fix) Add f288-models- detection to add 2 pages models
  workspace/utilities/lib/fx-url-creator.xsl
  workspace/utilities/site-variables.xsl
Labels: change requested, enhancement
