Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2019-01, with the labels that each got.

#313 Use ->getAuthToken() in Symphony v3
  workspace/events/event.login.php
Labels: bug, wait before merge

#318 new humans <3
  humans.txt
Labels: enhancement

#312 Warn if there is an error in Gruntcustom.js
  workspace/assets/Gruntfile.js
Labels: enhancement, ready to merge

#311 Run the curl task before uglify
  workspace/assets/Gruntfile.js
Labels: enhancement, ready to merge

#304 Add site credits component
  workspace/utilities/com/site-credits.xsl
Labels: enhancement, ready to merge

#320 Load css after async js
  workspace/utilities/master/master-head.xsl
Labels: enhancement

#319 Remove or fix broken xslt
  workspace/utilities/master/master.xsl
  workspace/utilities/master/variables.xsl
  workspace/utilities/recipes/recipe-custom.xsl
  workspace/utilities/recipes/recipe-typography.xsl
  workspace/utilities/recipes/recipes.xsl
Labels: bug, ready to merge

#321 Add fallback to position sticky for non compatible browsers
  workspace/assets/css/core/fct-position.less
Labels: enhancement, ready to merge
