Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2019-05, with the labels that each got.

#340 Add util image path
  workspace/utilities/lib/util-image-path.xsl
  workspace/utilities/site-imports.xsl
Labels: change requested, enhancement

#327 Add schema-search template
  workspace/utilities/com/schema-search.xsl
Labels: enhancement, need feedback, ready to merge

#342 Add status param for facebook share link
  workspace/utilities/lib/share-link.xsl
Labels: enhancement

#326 template cleanup and better use of site-variable
  workspace/utilities/com/schema-organization.xsl
Labels: enhancement, ready to merge
