Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2019-06, with the labels that each got.

#343 Picture template to replace render-image
  workspace/utilities/lib/picture.xsl
  workspace/utilities/master/master.xsl
Labels: need feedback, proposal

#276 Replace popup by struct modal
  workspace/utilities/lib/popup.xsl
  workspace/utilities/lib/struct-modal.xsl
Labels: enhancement, ready to merge

#352 Font display
  workspace/assets/css/core/fct-fonts.less
Labels: enhancement, ready to merge

#347 Pass params correctly
  workspace/utilities/com/module-embed-item.xsl
Labels: bug, ready to merge

#345 Add Dangligh Underscores _highlightResult exception
  workspace/assets/tasks/jscs.js
Labels: enhancement, ready to merge

#337 Added ulysse and francois
  humans.txt
Labels: enhancement, ready to merge
