Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2019-02, with the labels that each got.

#317 Replace nav-link with util-nav-link-attr
  workspace/utilities/com/site-nav.xsl
  workspace/utilities/lib/nav-link.xsl
  workspace/utilities/lib/util-nav-link-attr.xsl
  workspace/utilities/master/master.xsl
  workspace/utilities/site-imports.xsl
Labels: enhancement, ready to merge

#314 Watermark v3
  workspace/utilities/com/site-footer.xsl
  workspace/utilities/lib/copyright-288.xsl
  workspace/utilities/lib/iframe-copyright-288.xsl
  workspace/utilities/master/master.xsl
Labels: enhancement, need feedback, ready to merge

#329 Drop deprecated X-UA-Compatible
  workspace/utilities/master/master-head.xsl
Labels: ready to merge

#325 Add use case for type number
  workspace/utilities/lib/content.xsl
Labels: bug, ready to merge

#332 Fix typo error for class pointer-events-all-when-selected
  workspace/assets/css/lib/class-pointer-events.less
Labels: bug, ready to merge

#330 fix admin-tools svg on ie
  workspace/utilities/admin-tools/admin-tools.css
Labels: bug, ready to merge

#328 Remove deprecated (for a long time) ui-minimal
  workspace/utilities/master/master-head.xsl
Labels: bug, ready to merge

#290 Create basic module embed
  workspace/utilities/com/com-embed-video.xsl
  workspace/utilities/com/module-embed-item.xsl
  workspace/utilities/com/module-embed.xsl
  workspace/utilities/lib/oembed-attr.xsl
  workspace/utilities/lib/util-oembed-attr.xsl
  workspace/utilities/site-imports.xsl
Labels: enhancement, ready to merge

#333 js.json update for link-selector.js
  workspace/assets/js.json
Labels: enhancement, ready to merge

#331 Add class pointer-events-auto
  workspace/assets/css/lib/class-pointer-events.less
Labels: enhancement, ready to merge
