Repository DeuxHuitHuit/symphonycms-template, pull requests merged in 2020-06, with the labels that each got.

#467 Fixed node name
  workspace/utilities/lib/meta-theme.xsl
Labels: bug

#420 (chore) Load proper article changer
  workspace/assets/js.json
Labels: needs testing, ready to merge

#451 Use entry id instead of field name
  workspace/utilities/lib/util-form-id.xsl
Labels: enhancement, ready to merge

#469 Fixed attributes name for width and height
  workspace/utilities/lib/util-ficelle.xsl
Labels: bug

#474 Make admin tools hidden by default
  workspace/utilities/admin-tools/admin-tools.css
  workspace/utilities/admin-tools/admin-tools.xsl
Labels: bug

#476 New image template
  workspace/utilities/lib/image.xsl
  workspace/utilities/lib/picture.xsl
  workspace/utilities/lib/util-ficelle.xsl
  workspace/utilities/master/master.xsl
Labels: enhancement, proposal

#512 Full title update
  workspace/utilities/lib/full-title.xsl
Labels: bug

#515 Variables update
  workspace/utilities/master/variables.xsl
Labels: enhancement

#514 Meta description update
  workspace/utilities/lib/meta-description.xsl
Labels: bug

#506 fixed template name
  workspace/utilities/lib/meta-theme.xsl
Labels: bug, change requested

#507 removed jit code
  workspace/assets/js/utils/global.js
Labels: bug, change requested

#518 Ficelle template Update
  workspace/utilities/lib/util-ficelle.xsl
  workspace/utilities/site-imports.xsl
Labels: bug, change requested, enhancement
